[package]
name = "diskannrs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
bytemuck = "1.14"
memmap2 = "0.5"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
